packages:
  - 'apps/web/'
  - 'mobile/'
  - 'highlighter/'
  - 'packages/ui-common'
  - 'packages/tsconfig'
  - 'packages/tailwind-config'
  - 'packages/eslint-config-custom'
  - 'packages/ndk/ndk'
  - 'packages/ndk/ndk-cache-redis'
  - 'packages/ndk/ndk-cache-dexie'
  - 'packages/ndk/ndk-svelte'
  - 'packages/ndk/ndk-svelte-components'
  - 'packages/ndk/packages/*'
